spring:
  application:
    name: api-inventory-system
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_system_db
    username: postgres
    password: 2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
